name: run-tests

on: push

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: check
        run: |
          docker ps

      - name: Check out Git repository
        uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '9'

      - name: setup clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          # To use Clojure CLI 1.10.1.561 based on tools.deps
          cli: '1.10.1.469'

      - name: Cache maven
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('project.clj') }}
          restore-keys: |
            m2-

      - name: Test
        run: clj -A:test -A:runner
